# Generated by Django 5.1.15 on 2026-09-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='seed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
