# Generated by Django 5.1.15 on 2026-08-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField()),
                ('position', models.PositiveIntegerField()),
                ('is_bye', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('bye', 'Bye')], default='scheduled', max_length=20)),
                ('bracket_round_label', models.CharField(blank=True, default='', max_length=30)),
                ('team1_score', models.CharField(blank=True, default='', max_length=20)),
                ('team2_score', models.CharField(blank=True, default='', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'matches',
            },
        ),
    ]
